Repository gardener/etcd-druid, pull requests merged in 2020-04, with the labels that each got.

#34 Stop reconciliation of etcd resources on sts changes
  api/v1alpha1/etcd_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/controller_ref_manager.go
  controllers/etcd_controller.go
  controllers/etcd_controller_test.go
  vendor/github.com/gardener/gardener/pkg/utils/context/context.go
  vendor/github.com/gardener/gardener/pkg/utils/context/types.go
  vendor/github.com/gardener/gardener/pkg/utils/retry/alias.go
  vendor/github.com/gardener/gardener/pkg/utils/retry/retry.go
  vendor/github.com/gardener/gardener/pkg/utils/retry/types.go
  vendor/modules.txt
Labels: needs/ok-to-test

#35 Add priority class name, use same temp directory as before
  api/v1alpha1/etcd_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/etcd/templates/etcd-statefulset.yaml
  charts/etcd/values.yaml
  config/samples/druid_v1alpha1_etcd.yaml
  controllers/etcd_controller.go
  go.mod
  go.sum
Labels: reviewed/ok-to-test

#38 Pin k/k dependencies to v0.16.8
  .ci/pipeline_definitions
  Dockerfile
  Makefile
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/intstr/intstr.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/client-go/tools/record/event.go
  vendor/k8s.io/client-go/util/connrotation/connrotation.go
  vendor/modules.txt
Labels: needs/ok-to-test

#40 :sparkle: Populate system default root-ca-certificate with ca-bundle
  charts/etcd/templates/etcd-bootstrap-configmap.yaml
  charts/etcd/templates/etcd-statefulset.yaml
  controllers/etcd_controller.go
Labels: needs/ok-to-test

#37 Handle empty value for volumeClaimTemplate name
  .ci/pipeline_definitions
  api/v1alpha1/etcd_types.go
  controllers/etcd_controller.go
  controllers/etcd_controller_test.go
  go.mod
  go.sum
  pkg/utils/miscellaneous.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/README.md
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences_dummy.go
  vendor/modules.txt
Labels: needs/ok-to-test

#43 Accept 'openstack' for storage provider
  pkg/utils/miscellaneous.go
Labels: needs/ok-to-test

#42 Fixed call to get provider when store field is nil
  controllers/etcd_controller.go
Labels: needs/ok-to-test

#36 Change etcd crd definition.
  config/crd/bases/druid.gardener.cloud_etcds.yaml
Labels: needs/ok-to-test

#48 Removed owner reference from etcd statefulsets
  api/v1alpha1/etcd_types.go
  charts/etcd/templates/etcd-statefulset.yaml
  config/crd/bases/druid.gardener.cloud_etcds.yaml
  controllers/controller_ref_manager.go
  controllers/etcd_controller.go
  controllers/etcd_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  pkg/common/common.go
Labels: needs/ok-to-test, reviewed/ok-to-test

#49 Add sleep to ensure that etcd is added to reconcile queue
  controllers/etcd_controller_test.go
Labels: needs/ok-to-test, reviewed/ok-to-test

#51 [ci:component:github.com/gardener/etcd-backup-restore:0.8.0->v0.9.0]
  charts/images.yaml
Labels: reviewed/ok-to-test
