Repository gardener/etcd-druid, pull requests merged in 2020-05, with the labels that each got.

#55 Remove the cluster autooscaler safe-to-evict annotation from etcd sts.
  charts/etcd/templates/etcd-statefulset.yaml
Labels: kind/enhancement, reviewed/ok-to-test

#56 Added ci changes and updated etcdbrctl version
  .ci/pipeline_definitions
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#58 move update job to own pipeline
  .ci/pipeline_definitions
Labels: reviewed/ok-to-test
