Repository gardener/etcd-druid, pull requests merged in 2021-06, with the labels that each got.

#189 Updated the multi-node proposal.
  docs/proposals/multi-node/README.md
  docs/proposals/multi-node/etcd-backup-restore-work-flows-life-cycle.txt
  docs/proposals/multi-node/images/etcd-backup-restore-work-flows-life-cycle.png
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#188 Modularization & Status Enhancements
  .ci/test
  api/v1alpha1/etcd_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/druid.gardener.cloud_etcds.yaml
  controllers/config/custodian.go
  controllers/controllers_suite_test.go
  controllers/etcd_controller.go
  controllers/etcd_controller_test.go
  controllers/etcd_custodian_controller.go
  main.go
  pkg/health/condition/builder.go
  pkg/health/condition/builder_test.go
  pkg/health/condition/check_all_members.go
  pkg/health/condition/check_all_members_test.go
  pkg/health/condition/check_ready.go
  pkg/health/condition/check_ready_test.go
  pkg/health/condition/condition_suite_test.go
  pkg/health/condition/types.go
  pkg/health/etcdmember/builder.go
  pkg/health/etcdmember/builder_test.go
  pkg/health/etcdmember/check_ready.go
  pkg/health/etcdmember/check_ready_test.go
  pkg/health/etcdmember/etcdmember_suite_test.go
  pkg/health/etcdmember/types.go
  pkg/health/status/check.go
  pkg/health/status/check_test.go
  pkg/health/status/status_suite_test.go
  pkg/utils/miscellaneous.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/etcd_types.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/zz_generated.deepcopy.go
Labels: area/control-plane, kind/enhancement, lifecycle/stale, needs/ok-to-test, needs/review, needs/second-opinion, size/xl, status/author-action

#190 Enable profiling of etcd-backup-restore-sidecar
  api/v1alpha1/etcd_types.go
  charts/etcd/templates/etcd-statefulset.yaml
  charts/etcd/values.yaml
  config/crd/bases/druid.gardener.cloud_etcds.yaml
  controllers/etcd_controller.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/etcd_types.go
Labels: needs/review, needs/second-opinion, size/xs

#192 Fix failing make check-generate
  api/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/zz_generated.deepcopy.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
