Repository gardener/etcd-druid, pull requests merged in 2021-05, with the labels that each got.

#174 Removed synchronisation before updating ETCD status.
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/etcd_controller.go
  controllers/etcd_custodian_controller.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/zz_generated.deepcopy.go
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#175 Update pipeline images to Golang 1.16.4
  .ci/pipeline_definitions
Labels: area/delivery, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#176 Removed synchronisation before updating ETCD status.
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/etcd_controller.go
  controllers/etcd_custodian_controller.go
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#177 Introduce make check-generate
  .ci/check
  Makefile
  controllers/etcd_controller_test.go
  hack/update-codegen.sh
Labels: area/dev-productivity, area/robustness, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#182 Upgrade github_com_gardener_etcd-backup-restore to v0.12.1
  charts/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#183 Upgrade github_com_gardener_etcd-backup-restore to v0.12.1
  charts/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs
