Repository gardener/etcd-druid, pull requests merged in 2021-03, with the labels that each got.

#115 Proposal to support multi-node etcd clusters
  docs/proposals/multi-node/README.md
  docs/proposals/multi-node/etcd-backup-restore-work-flows-life-cycle.txt
  docs/proposals/multi-node/etcd-member-initialization-sequence.txt
  docs/proposals/multi-node/images/etcd-backup-restore-work-flows-life-cycle.png
  docs/proposals/multi-node/images/etcd-member-initialization-sequence.png
  docs/proposals/multi-node/images/multinodeetcd.png
  docs/proposals/multi-node/multinodeetcd.drawio
  hack/print-content.sh
Labels: needs/ok-to-test, needs/second-opinion, size/xl

#139 Update pipeline images
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#150 Fix pipeline check
  .ci/check
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
Labels: area/delivery, kind/bug, needs/ok-to-test, needs/review, size/s

#146 Read PVC warning events
  controllers/etcd_controller.go
  controllers/etcd_controller_test.go
  controllers/suite_test.go
  main.go
  vendor/github.com/gardener/gardener/extensions/pkg/util/test/options.go
  vendor/github.com/gardener/gardener/extensions/pkg/util/test/test.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/flow.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/graph.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/progress_reporter.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/progress_reporter_delaying.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/progress_reporter_immediate.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/taskfn.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/taskid.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/bootstrap_token.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/controllerinstallation.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/controllerregistration.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/daemonset.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/deployment.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/etcd.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/kubernetes.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/leaderelection.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/managedseed.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/namespace.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/object.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/patch.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/project.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/secretref.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/seed.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/service.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/shoot.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/sorter.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/statefulset.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/update.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/worker.go
  vendor/github.com/gardener/gardener/pkg/utils/test/matchers/deep.go
  vendor/github.com/gardener/gardener/pkg/utils/test/matchers/fields.go
  vendor/github.com/gardener/gardener/pkg/utils/test/matchers/kubernetes_errors.go
  vendor/github.com/gardener/gardener/pkg/utils/test/matchers/matchers.go
  vendor/k8s.io/apimachinery/pkg/util/duration/duration.go
  vendor/k8s.io/cluster-bootstrap/LICENSE
  vendor/k8s.io/cluster-bootstrap/token/api/doc.go
  vendor/k8s.io/cluster-bootstrap/token/api/types.go
  vendor/k8s.io/cluster-bootstrap/token/util/helpers.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#138 Integrate the etcdbr-compression feature from etcd-backup-restore with etcd-druid.
  api/v1alpha1/etcd_types.go
  charts/etcd/templates/etcd-statefulset.yaml
  charts/etcd/values.yaml
  config/crd/bases/druid.gardener.cloud_etcds.yaml
  config/samples/druid_v1alpha1_etcd.yaml
  controllers/etcd_controller.go
Labels: needs/ok-to-test, needs/review, size/s
