Repository gardener/etcd-druid, pull requests merged in 2022-05, with the labels that each got.

#339 [Bug] Update func to return correct max value
  pkg/utils/miscellaneous.go
Labels: needs/ok-to-test, needs/review, size/xs

#345 Upgrade etcd-backup-restore:v0.15.2->v0.15.3
  charts/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#344 Updated configmap reconciliation to consider alternate labels added b…
  controllers/etcd_controller.go
Labels: area/backup, kind/bug, needs/ok-to-test, needs/changes, needs/review, size/xs

#342 Fix etcd resource limits for existing clusters
  controllers/etcd_controller.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#346 [cherry-pick#342] Fix etcd resource limits for existing clusters
  controllers/etcd_controller.go
Labels: kind/bug, needs/ok-to-test, needs/review, size/xs

#336 fix deployment issue of etcd druid
  config/crd/kustomization.yaml
  config/default/manager_image_patch.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  config/samples/druid_v1alpha1_etcd.yaml
Labels: needs/ok-to-test, needs/changes, size/m

#348 component:github.com/gardener/etcd-backup-restore:v0.15.3->v0.15.4
  charts/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#302 Update manifest.yaml
  .docforge/manifest.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
