Repository gardener/etcd-druid, pull requests merged in 2022-03, with the labels that each got.

#305 Upgrade etcd-backup-restore to v0.15.0
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#285 Integrate leader-election feature with etcd-druid.
  api/v1alpha1/etcd_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/etcd/templates/etcd-statefulset.yaml
  charts/etcd/values.yaml
  config/crd/bases/10-crd-druid.gardener.cloud_etcds.yaml
  config/samples/druid_v1alpha1_etcd.yaml
  controllers/etcd_controller.go
Labels: needs/ok-to-test, reviewed/lgtm, reviewed/do-not-merge, size/s

#301 To dynamically load IaaS credentials during runtime using secrets mount.
  charts/etcd-copy-backups/templates/etcd-copy-backups-job.yaml
  charts/etcd/templates/etcd-statefulset.yaml
  controllers/compaction_lease_controller.go
  controllers/compaction_lease_controller_test.go
  controllers/etcd_controller_test.go
  controllers/etcdcopybackupstask_controller_test.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xl

#306 Fix the bug to avoid Nil pointer exception in EtcdCopyBackupsTask.
  controllers/etcdcopybackupstask_controller.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#300 Add support for ETCD backups in the local provider extension
  charts/etcd-copy-backups/templates/etcd-copy-backups-job.yaml
  charts/etcd/templates/etcd-statefulset.yaml
  config/rbac/role.yaml
  controllers/etcd_controller.go
  controllers/etcd_controller_test.go
  controllers/etcdcopybackupstask_controller.go
  pkg/utils/miscellaneous.go
Labels: area/backup, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m

#308 Removed some unnecessary RBAC.
  config/rbac/role.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#313 Revert "Updated configmap mountpoints based on ETCD replicas."
  api/v1alpha1/etcd_types.go
  api/v1alpha1/etcd_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/etcd/templates/etcd-configmap.yaml
  charts/etcd/templates/etcd-statefulset.yaml
  charts/etcd/values.yaml
  config/crd/bases/10-crd-druid.gardener.cloud_etcds.yaml
  config/default/manager_image_patch.yaml
  config/rbac/leader_election_role.yaml
  controllers/compaction_lease_controller.go
  controllers/compaction_lease_controller_test.go
  controllers/controller_ref_manager.go
  controllers/etcd_controller.go
  controllers/etcd_controller_test.go
  pkg/component/etcd/configmap/configmap.go
  pkg/component/etcd/configmap/configmap_suite_test.go
  pkg/component/etcd/configmap/configmap_test.go
  pkg/component/etcd/configmap/values.go
  pkg/component/etcd/configmap/values_helper.go
  pkg/component/etcd/lease/lease.go
  pkg/component/etcd/service/values_helper.go
  pkg/component/etcd/values.go
  pkg/utils/names.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#312 Remove default CPU and memory limits
  charts/etcd/values.yaml
  controllers/etcd_controller_test.go
Labels: needs/ok-to-test, needs/review, size/xs

#310 Add secret controller to ensure finalizers for referenced secrets
  config/rbac/role.yaml
  controllers/controllers_suite_test.go
  controllers/etcd_controller.go
  controllers/secret_controller.go
  controllers/secret_controller_test.go
  main.go
  pkg/mapper/etcd_to_secret.go
  pkg/mapper/etcd_to_secret_test.go
  pkg/mapper/statefulset_to_etcd.go
  pkg/mapper/statefulset_to_etcd_test.go
Labels: area/usability, kind/bug, needs/ok-to-test, needs/review, needs/second-opinion, size/l, merge/squash

#309 [GEP-18] Make CA certificate data key configurable
  api/v1alpha1/etcd_types.go
  api/v1alpha1/etcd_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/etcd/templates/etcd-configmap.yaml
  charts/etcd/templates/etcd-statefulset.yaml
  charts/etcd/values.yaml
  charts/images.yaml
  config/crd/bases/10-crd-druid.gardener.cloud_etcds.yaml
  controllers/etcd_controller.go
  controllers/etcd_controller_test.go
  pkg/mapper/etcd_to_secret_test.go
Labels: area/security, kind/enhancement, needs/ok-to-test, needs/review, size/s, merge/squash

#311 Added required RBAC which was mistakenly removed.
  config/rbac/role.yaml
  controllers/etcd_controller.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#317 [hotfix-v0.8] Reconcile `ServiceAccount`'s `automountServiceAccountToken` field
  controllers/etcd_controller.go
  controllers/secret_controller.go
Labels: area/security, kind/bug, needs/ok-to-test, needs/review, size/xs

#316 Reconcile `ServiceAccount`'s `automountServiceAccountToken` field
  controllers/etcd_controller.go
  controllers/secret_controller.go
Labels: area/security, kind/bug, needs/ok-to-test, needs/review, size/xs
