Repository gardener/etcd-druid, pull requests merged in 2022-07, with the labels that each got.

#360 Change base image from alpine to distroless
  Dockerfile
Labels: area/open-source, area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#370 github.com/gardener/etcd-custom-image:v3.4.13-bootstrap-5->v3.4.13-bootstrap-6
  charts/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#380 [ci:component:github.com/gardener/etcd-backup-restore:v0.18.0->v0.18.1]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#379 Added pod permissions in etcd-role
  charts/etcd/templates/etcd-role.yaml
  controllers/etcd_controller_test.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#377 [CI] Release Improvements
  .ci/bump_tag
  .ci/pipeline_definitions
  config/default/manager_image_patch.yaml
Labels: area/delivery, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#375 Update to Golang 1.18.4
  .ci/pipeline_definitions
  Dockerfile
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#381 Fix golangci for 1.18
  .golangci.yaml
  Makefile
Labels: area/delivery, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#385 [ci:component:github.com/gardener/etcd-backup-restore:v0.18.1->v0.18.2]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#388 Add service-endpoints to etcd-br
  charts/etcd/templates/etcd-statefulset.yaml
  controllers/etcd_controller.go
  controllers/etcd_controller_test.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs
