Repository gardener/etcd-druid, pull requests merged in 2022-08, with the labels that each got.

#376 Added a design doc for single-member restoration in multi-node cluster.
  docs/single_member_restoration.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#365 Deploy statefulset as component.
  controllers/compaction_lease_controller.go
  controllers/compaction_lease_controller_test.go
  controllers/controller_ref_manager.go
  controllers/controllers_suite_test.go
  controllers/etcd_controller.go
  controllers/etcd_controller_test.go
  controllers/etcd_custodian_controller.go
  pkg/component/etcd/lease/values_helper.go
  pkg/component/etcd/statefulset/statefulset.go
  pkg/component/etcd/statefulset/statefulset_suite_test.go
  pkg/component/etcd/statefulset/statefulset_test.go
  pkg/component/etcd/statefulset/values.go
  pkg/component/etcd/statefulset/values_helper.go
  pkg/component/etcd/values.go
  pkg/utils/miscellaneous.go
  pkg/utils/names.go
  pkg/utils/statefulset.go
Labels: area/robustness, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xl

#383 Added etcd network latency analysis
  docs/etcd-network-latency.md
Labels: area/documentation, needs/ok-to-test, reviewed/lgtm, size/l

#394 Add missing service-endpoints to sts component
  pkg/component/etcd/statefulset/statefulset.go
  pkg/component/etcd/statefulset/statefulset_test.go
  pkg/component/etcd/statefulset/values.go
  pkg/component/etcd/statefulset/values_helper.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#389 Clarify `etcd.status.ready` field
  api/v1alpha1/etcd_types.go
  config/crd/bases/10-crd-druid.gardener.cloud_etcds.yaml
Labels: area/usability, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#396 Fix liveness and readiness probes
  controllers/etcd_controller_test.go
  hack/test.sh
  pkg/component/etcd/statefulset/statefulset.go
  pkg/component/etcd/statefulset/statefulset_test.go
  pkg/component/etcd/statefulset/values.go
  pkg/component/etcd/statefulset/values_helper.go
Labels: area/quality, kind/bug, needs/ok-to-test, reviewed/lgtm, reviewed/do-not-merge, size/l

#393 StatefulSet component follow ups
  charts/etcd/templates/etcd-statefulset.yaml
  charts/etcd/values.yaml
  controllers/etcd_controller.go
  pkg/component/etcd/statefulset/statefulset.go
  pkg/component/etcd/statefulset/values.go
  pkg/component/etcd/values.go
Labels: area/quality, kind/technical-debt, needs/ok-to-test, needs/second-opinion, size/xl

#397 Fix issue with release callback for the bump_tag script
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#398 Fix .ci/bump_tag permissions
  .ci/bump_tag
Labels: area/ops-productivity, kind/bug, needs/ok-to-test, needs/review, size/xs

#399 Fix .ci/bump_tag script
  .ci/bump_tag
Labels: area/ops-productivity, kind/bug, needs/review, reviewed/ok-to-test, size/xs

#401 Fix storage class in statefulset
  pkg/component/etcd/statefulset/statefulset.go
Labels: area/backup, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#402 Fix PodManagementPolicy updation for etcd statefulset
  pkg/component/etcd/statefulset/statefulset.go
Labels: area/backup, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#403 Fix ServiceName updation for etcd statefulset
  pkg/component/etcd/statefulset/statefulset.go
Labels: area/backup, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#400 Fix storage class in statefulset
  pkg/component/etcd/statefulset/statefulset.go
Labels: area/backup, kind/bug, needs/ok-to-test, needs/review, size/xs

#406 [rel-v0.12] Fix podManagementPolicy for scale-up scenario
  pkg/component/etcd/statefulset/statefulset.go
  pkg/component/etcd/statefulset/statefulset_test.go
Labels: area/high-availability, kind/bug, needs/ok-to-test, reviewed/lgtm, size/s

#408 Fix serviceName and podManagementPolicy field updates
  pkg/component/etcd/statefulset/statefulset.go
  pkg/component/etcd/statefulset/statefulset_test.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, reviewed/lgtm, size/s

#412 Fix local provider
  controllers/compaction_lease_controller.go
  controllers/etcdcopybackupstask_controller.go
  pkg/component/etcd/statefulset/statefulset.go
  pkg/component/etcd/statefulset/statefulset_test.go
  pkg/component/etcd/statefulset/values_helper.go
  pkg/utils/miscellaneous.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, needs/review, size/m
