Repository gardener/etcd-druid, pull requests merged in 2022-12, with the labels that each got.

#462 Fix make manifest target
  charts/druid/charts/crds/templates/10-crd-druid.gardener.cloud_etcds.yaml
  config/crd/bases/10-crd-druid.gardener.cloud_etcds.yaml
  config/rbac/role.yaml
  controllers/compaction_lease_controller.go
  controllers/etcd_controller.go
  controllers/etcd_custodian_controller.go
  controllers/etcdcopybackupstask_controller.go
  controllers/secret_controller.go
Labels: area/usability, kind/technical-debt, needs/ok-to-test, reviewed/lgtm, size/m

#489 Fix `make manifests` target
  charts/druid/charts/crds/templates/10-crd-druid.gardener.cloud_etcds.yaml
  config/crd/bases/10-crd-druid.gardener.cloud_etcds.yaml
  config/rbac/role.yaml
  controllers/compaction_lease_controller.go
  controllers/etcd_controller.go
  controllers/etcd_custodian_controller.go
  controllers/etcdcopybackupstask_controller.go
  controllers/secret_controller.go
Labels: area/usability, kind/bug, kind/technical-debt, needs/ok-to-test, needs/review, size/m

#488 Removed unnecessary step from playbook to recover from quorum loss.
  docs/operation/Recover_From_Etcd_Permanent_Quorum_Loss.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, merge/squash

#485 Allow specifying labels for the etcd client Service
  api/v1alpha1/etcd_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/druid/charts/crds/templates/10-crd-druid.gardener.cloud_etcds.yaml
  config/crd/bases/10-crd-druid.gardener.cloud_etcds.yaml
  pkg/component/etcd/service/service_client.go
  pkg/component/etcd/service/values.go
  pkg/component/etcd/service/values_helper.go
  pkg/component/etcd/service/values_helper_test.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, size/s

#491 Automated cherry pick of #485: Allow specifying labels for the etcd client Service
  api/v1alpha1/etcd_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/druid/charts/crds/templates/10-crd-druid.gardener.cloud_etcds.yaml
  config/crd/bases/10-crd-druid.gardener.cloud_etcds.yaml
  pkg/component/etcd/service/service_client.go
  pkg/component/etcd/service/values.go
  pkg/component/etcd/service/values_helper.go
  pkg/component/etcd/service/values_helper_test.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/review, size/s

#493 Remove `CustomReporter` from envtest
  api/v1alpha1/suite_test.go
  controllers/controllers_suite_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/printer/ginkgo.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/printer/prow.go
Labels: area/open-source, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#486 Removed `corrupt etcd db` e2e tests.
  test/e2e/etcd_multi_node_test.go
Labels: kind/bug, reviewed/lgtm, size/xs, area/testing

#490 Enhance `kubectl` printer columns for etcd resource
  api/v1alpha1/etcd_types.go
  charts/druid/charts/crds/templates/10-crd-druid.gardener.cloud_etcds.yaml
  config/crd/bases/10-crd-druid.gardener.cloud_etcds.yaml
Labels: area/usability, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#492 Minor fixes and improvements
  README.md
  config/samples/druid_v1alpha1_etcd.yaml
Labels: area/dev-productivity, area/quality, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#461 Removes owner checks
  api/v1alpha1/etcd_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/validation/etcd.go
  api/validation/etcd_test.go
  charts/druid/charts/crds/templates/10-crd-druid.gardener.cloud_etcds.yaml
  config/crd/bases/10-crd-druid.gardener.cloud_etcds.yaml
  controllers/etcd_controller_test.go
  pkg/component/etcd/statefulset/statefulset_test.go
  pkg/component/etcd/statefulset/values.go
  pkg/component/etcd/statefulset/values_helper.go
Labels: kind/cleanup, needs/ok-to-test, needs/review, size/m, area/control-plane-migration
