Repository gardener/etcd-druid, pull requests merged in 2022-04, with the labels that each got.

#319 Mounted peer certificates in backup-restore pod.
  charts/etcd/templates/etcd-statefulset.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#327 Upgrade etcd-backup-restore:v0.15.0->v0.15.1
  charts/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#329 Add SchedulingConstraints to Etcd spec
  api/v1alpha1/etcd_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/etcd/templates/etcd-statefulset.yaml
  charts/etcd/values.yaml
  config/crd/bases/10-crd-druid.gardener.cloud_etcds.yaml
  config/samples/druid_v1alpha1_etcd.yaml
  controllers/etcd_controller.go
Labels: area/high-availability, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xl

#331 Disable member lease renewal
  charts/etcd/templates/etcd-statefulset.yaml
  controllers/etcd_controller_test.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#337 Disable member lease update
  charts/etcd/templates/etcd-statefulset.yaml
  controllers/etcd_controller_test.go
Labels: needs/ok-to-test

#338 Upgrade etcd-backup-restore:v0.15.1->v0.15.2
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
