Repository gardener/etcd-druid, pull requests merged in 2022-11, with the labels that each got.

#430 Handle PDB API version upgrade
  charts/etcd/templates/etcd-poddisruptionbudget.yaml
  controllers/controller_ref_manager.go
  controllers/controllers_suite_test.go
  controllers/etcd_controller.go
  controllers/etcd_controller_test.go
  controllers/etcd_custodian_controller.go
  controllers/etcd_custodian_controller_test.go
  go.mod
  pkg/component/etcd/poddisruptionbudget/poddisruptionbudget.go
  pkg/component/etcd/poddisruptionbudget/poddisruptionbudget_suite_test.go
  pkg/component/etcd/poddisruptionbudget/poddisruptionbudget_test.go
  pkg/component/etcd/poddisruptionbudget/values.go
  pkg/component/etcd/poddisruptionbudget/valueshelper.go
  pkg/component/etcd/poddisruptionbudget/valueshelper_test.go
  pkg/utils/k8s_version.go
  pkg/utils/utils_suite_test.go
  pkg/utils/utils_test.go
Labels: area/control-plane, kind/api-change, kind/cleanup, needs/ok-to-test, needs/second-opinion, size/xl

#446 Stopped reconciliation if quorumloss annotation is set by operator.
  controllers/etcd_controller.go
  controllers/etcd_controller_test.go
  docs/operation/Recover_From_Etcd_Permanent_Quorum_Loss.md
Labels: area/high-availability, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m

#455 Update condition to add ScaleToMultiNode annotation
  pkg/component/etcd/statefulset/statefulset.go
Labels: area/robustness, kind/bug, needs/ok-to-test, needs/review, size/xs

#451 Added e2e tests for single member restoration
  test/e2e/etcd_multi_node_test.go
  test/e2e/suite_test.go
  test/e2e/utils.go
Labels: kind/enhancement, needs/ok-to-test, needs/changes, needs/review, size/m, area/testing

#463 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: area/documentation, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#466 Updated condition that adds the scale-up annotation to the sts
  pkg/component/etcd/statefulset/statefulset.go
Labels: area/disaster-recovery, area/high-availability, kind/bug, needs/ok-to-test, needs/review, size/xs, needs/cherry-pick

#468 [hotfix-0.14] Updated condition that adds the scale-up annotation to the sts (#466)
  pkg/component/etcd/statefulset/statefulset.go
Labels: area/disaster-recovery, area/high-availability, kind/bug, needs/ok-to-test, needs/review, size/xs

#469 Fix backup ready health check
  pkg/health/condition/check_backup_ready.go
  pkg/health/condition/check_backup_ready_test.go
Labels: area/ops-productivity, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#460 Upgrade Dockerfile and pipeline to use golang 1.19.2
  .ci/pipeline_definitions
  Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#474 Update golangci-lint version and bump golang to `v1.19`
  .ci/pipeline_definitions
  .golangci.yaml
  Makefile
  controllers/compaction_lease_controller_test.go
  controllers/controller_ref_manager.go
  go.mod
  pkg/utils/miscellaneous.go
Labels: area/quality, kind/bug, needs/ok-to-test, needs/changes, needs/review, size/s

#472 Fix druid clusterrole PDB permission
  charts/druid/templates/druid-clusterrole.yaml
Labels: area/backup, kind/bug, needs/ok-to-test, needs/review, size/xs, merge/squash

#458 fix serviceaccount name in chart
  charts/druid/templates/service-account.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#448 Harmonize kustomizations
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s
