Repository gardener/etcd-druid, pull requests merged in 2023-03, with the labels that each got.

#548 etcd-backup-restore:v0.22.0->v0.22.1
  charts/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs, status/accepted

#549 correctly set set-permissions as prerequisute rule for other make rules
  .github/pull_request_template.md
  Makefile
  vendor/github.com/gardener/gardener/hack/.ci/component_descriptor
  vendor/github.com/gardener/gardener/hack/.ci/doc.go
  vendor/github.com/gardener/gardener/hack/.ci/prepare_release
  vendor/github.com/gardener/gardener/hack/.ci/set_dependency_version
  vendor/github.com/gardener/gardener/hack/LICENSE_BOILERPLATE.txt
  vendor/github.com/gardener/gardener/hack/check-apidiff.sh
  vendor/github.com/gardener/gardener/hack/check-charts.sh
  vendor/github.com/gardener/gardener/hack/check-docforge.sh
  vendor/github.com/gardener/gardener/hack/check-imports.sh
  vendor/github.com/gardener/gardener/hack/check-skaffold-deps.sh
  vendor/github.com/gardener/gardener/hack/cherry-pick-pull.sh
  vendor/github.com/gardener/gardener/hack/ci-common.sh
  vendor/github.com/gardener/gardener/hack/ci-e2e-kind-ha-multi-zone.sh
  vendor/github.com/gardener/gardener/hack/ci-e2e-kind-ha-single-zone.sh
  vendor/github.com/gardener/gardener/hack/ci-e2e-kind-migration.sh
  vendor/github.com/gardener/gardener/hack/ci-e2e-kind-operator.sh
  vendor/github.com/gardener/gardener/hack/ci-e2e-kind-upgrade.sh
  vendor/github.com/gardener/gardener/hack/ci-e2e-kind.sh
  vendor/github.com/gardener/gardener/hack/compare-k8s-admission-plugins.sh
  vendor/github.com/gardener/gardener/hack/compare-k8s-controllers.sh
  vendor/github.com/gardener/gardener/hack/compare-k8s-feature-gates.sh
  vendor/github.com/gardener/gardener/hack/download_gardener_source_code.sh
  vendor/github.com/gardener/gardener/hack/format.sh
  vendor/github.com/gardener/gardener/hack/gardener-down.sh
  vendor/github.com/gardener/gardener/hack/gardener-extensions-down.sh
  vendor/github.com/gardener/gardener/hack/gardener-extensions-up.sh
  vendor/github.com/gardener/gardener/hack/generate-controller-registration.sh
  vendor/github.com/gardener/gardener/hack/generate-imagename-constants.sh
  vendor/github.com/gardener/gardener/hack/generate-monitoring-docs.sh
  vendor/github.com/gardener/gardener/hack/generate-parallel.sh
  vendor/github.com/gardener/gardener/hack/generate.sh
  vendor/github.com/gardener/gardener/hack/get-build-ld-flags.sh
  vendor/github.com/gardener/gardener/hack/hook-me.sh
  vendor/github.com/gardener/gardener/hack/install.sh
  vendor/github.com/gardener/gardener/hack/kind-down.sh
  vendor/github.com/gardener/gardener/hack/kind-extensions-up.sh
  vendor/github.com/gardener/gardener/hack/kind-up.sh
  vendor/github.com/gardener/gardener/hack/prepare-envtest.sh
  vendor/github.com/gardener/gardener/hack/start-envtest.sh
  vendor/github.com/gardener/gardener/hack/test-cover-clean.sh
  vendor/github.com/gardener/gardener/hack/test-cover.sh
  vendor/github.com/gardener/gardener/hack/test-e2e-local.env
  vendor/github.com/gardener/gardener/hack/test-e2e-local.sh
  vendor/github.com/gardener/gardener/hack/test-integration.env
  vendor/github.com/gardener/gardener/hack/test-integration.sh
  vendor/github.com/gardener/gardener/hack/test-prometheus.sh
  vendor/github.com/gardener/gardener/hack/test.sh
  vendor/github.com/gardener/gardener/hack/tools.go
  vendor/github.com/gardener/gardener/hack/tools.mk
  vendor/github.com/gardener/gardener/hack/update-codegen.sh
  vendor/github.com/gardener/gardener/hack/update-protobuf.sh
Labels: area/dev-productivity, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#541 Installing `kustomize` dependency for `Etcd-druid`
  Makefile
  hack/tools.mk
Labels: area/dev-productivity, area/robustness, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#522 Hvpa-controller dependency update
  go.mod
  go.sum
  vendor/github.com/gardener/hvpa-controller/LICENSE.md
  vendor/github.com/gardener/hvpa-controller/api/v1alpha1/groupversion_info.go
  vendor/github.com/gardener/hvpa-controller/api/v1alpha1/hvpa_types.go
  vendor/github.com/gardener/hvpa-controller/api/v1alpha1/hvpa_webhook.go
  vendor/github.com/gardener/hvpa-controller/api/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/doc.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/register.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/types.go
  vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1beta2/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: area/quality, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#562 Added etcd-druid-api content
  .docforge/manifest.yaml
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/review, reviewed/ok-to-test, size/xs

#558 Minor cosmetics and streamlining after controller-runtime refactoring
  controllers/compaction/register.go
  controllers/custodian/register.go
  controllers/etcd/register.go
  controllers/etcdcopybackupstask/register.go
  controllers/secret/register.go
Labels: area/quality, area/robustness, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#535 Refactor `ServiceAccount` Helm charts into component
  api/v1alpha1/types_etcd.go
  charts/etcd/templates/etcd-serviceaccount.yaml
  controllers/etcd/reconciler.go
  pkg/component/etcd/serviceaccount/serviceaccount.go
  pkg/component/etcd/serviceaccount/serviceaccount_suite_test.go
  pkg/component/etcd/serviceaccount/serviceaccount_test.go
  pkg/component/etcd/serviceaccount/values.go
  pkg/component/etcd/serviceaccount/values_helper.go
  pkg/component/etcd/serviceaccount/values_helper_test.go
Labels: area/robustness, kind/enhancement, needs/ok-to-test, needs/second-opinion, size/xl
