Repository gardener/etcd-druid, pull requests merged in 2023-09, with the labels that each got.

#675 Add etcd-druid logo
  README.md
  logo/etcd-druid-logo.png
Labels: area/documentation, area/open-source, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#671 Optimize Registration Logic for Snapshot Compaction controller
  controllers/compaction/reconciler.go
  controllers/manager.go
Labels: area/storage, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#658 [DEP-04] EtcdMember Custom Resource
  docs/proposals/04-etcd-member-custom-resource.md
  docs/proposals/assets/04-state-transitions-bootstrap-0-1.excalidraw.png
  docs/proposals/assets/04-state-transitions-restart-member.excalidraw.png
  docs/proposals/assets/04-state-transitions-scaleup-1-n.excalidraw.png
  docs/proposals/assets/04-top-level-state-transitions.excalidraw.png
Labels: area/quality, area/robustness, kind/enhancement, needs/ok-to-test, needs/second-opinion, reviewed/do-not-merge, size/xl

#672 Use better naming for compaction jobs
  api/v1alpha1/types_etcd.go
  api/v1alpha1/types_etcd_test.go
  controllers/compaction/metrics.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/lgtm, reviewed/do-not-merge, size/xs
