Repository gardener/etcd-druid, pull requests merged in 2023-06, with the labels that each got.

#605 Updated structure & frontmatter
  .docforge/manifest.yaml
  docs/development/local-e2e-tests.md
  docs/etcd-network-latency.md
  docs/operation/Recover_From_Etcd_Permanent_Quorum_Loss.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#559 Refactor components to use default labels and owner references from `etcd`
  api/v1alpha1/types_etcd_test.go
  controllers/compaction/reconciler.go
  controllers/etcd/reconciler.go
  controllers/etcdcopybackupstask/reconciler_test.go
  go.mod
  pkg/component/etcd/configmap/configmap.go
  pkg/component/etcd/configmap/configmap_suite_test.go
  pkg/component/etcd/configmap/configmap_test.go
  pkg/component/etcd/configmap/values.go
  pkg/component/etcd/configmap/values_helper.go
  pkg/component/etcd/lease/lease.go
  pkg/component/etcd/lease/lease_member.go
  pkg/component/etcd/lease/lease_snapshot.go
  pkg/component/etcd/lease/lease_test.go
  pkg/component/etcd/lease/values.go
  pkg/component/etcd/lease/values_helper.go
  pkg/component/etcd/poddisruptionbudget/poddisruptionbudget.go
  pkg/component/etcd/poddisruptionbudget/poddisruptionbudget_suite_test.go
  pkg/component/etcd/poddisruptionbudget/poddisruptionbudget_test.go
  pkg/component/etcd/poddisruptionbudget/values.go
  pkg/component/etcd/poddisruptionbudget/values_helper.go
  pkg/component/etcd/poddisruptionbudget/values_helper_test.go
  pkg/component/etcd/role/role.go
  pkg/component/etcd/role/role_test.go
  pkg/component/etcd/role/values.go
  pkg/component/etcd/role/values_helper.go
  pkg/component/etcd/role/values_helper_test.go
  pkg/component/etcd/rolebinding/rolebinding.go
  pkg/component/etcd/rolebinding/rolebinding_test.go
  pkg/component/etcd/rolebinding/values.go
  pkg/component/etcd/rolebinding/values_helper.go
  pkg/component/etcd/rolebinding/values_helper_test.go
  pkg/component/etcd/service/service.go
  pkg/component/etcd/service/service_client.go
  pkg/component/etcd/service/service_peer.go
  pkg/component/etcd/service/service_test.go
  pkg/component/etcd/service/values.go
  pkg/component/etcd/service/values_helper.go
  pkg/component/etcd/service/values_helper_test.go
  pkg/component/etcd/serviceaccount/serviceaccount.go
  pkg/component/etcd/serviceaccount/serviceaccount_suite_test.go
  pkg/component/etcd/serviceaccount/serviceaccount_test.go
  pkg/component/etcd/serviceaccount/values.go
  pkg/component/etcd/serviceaccount/values_helper.go
  pkg/component/etcd/serviceaccount/values_helper_test.go
  pkg/component/etcd/statefulset/statefulset.go
  pkg/component/etcd/statefulset/statefulset_suite_test.go
  pkg/component/etcd/statefulset/statefulset_test.go
  pkg/component/etcd/statefulset/values.go
  pkg/component/etcd/statefulset/values_helper.go
  pkg/utils/statefulset.go
  test/integration/controllers/compaction/reconciler_test.go
  test/integration/controllers/etcd/reconciler_test.go
  test/integration/controllers/etcdcopybackupstask/reconciler_test.go
  test/integration/controllers/secret/reconciler_test.go
  test/utils/etcdcopybackupstask.go
  test/utils/lease.go
  test/utils/statefulset.go
Labels: area/robustness, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xl

#614 Fixed broken link - 2023.06
  docs/proposals/multi-node/README.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#617 Optimize test runs by running lint check once
  Makefile
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#611 Adds e2e tests for scale-up feature: moving from non-HA(peer TLS not enable) -> HA (peerUrl TLS enable)
  charts/druid/templates/druid-clusterrole.yaml
  test/e2e/etcd_multi_node_test.go
  test/e2e/utils.go
Labels: kind/enhancement, kind/test, needs/ok-to-test, reviewed/lgtm, size/s

#623 Bumped up the custom image version to v3.4.13-bootstrap-11 in Druid.
  charts/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#624 Bumped up the custom image version to v3.4.13-bootstrap-11 in Druid.
  Makefile
  charts/images.yaml
  hack/e2e-test/infrastructure/kind/cluster.yaml
  hack/e2e-test/run-e2e-test.sh
  hack/kind-up.sh
  hack/test.sh
Labels: needs/ok-to-test, needs/review, size/s

#616 Updated the docforge manifest & added index files
  .docforge/manifest.yaml
  docs/development/_index.md
  docs/operation/_index.md
  docs/proposals/_index.md
  docs/proposals/multi-node/README.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#625 Cherry-picked compaction metrics commits to the hotfix branch
  controllers/compaction/metrics.go
  controllers/compaction/reconciler.go
  docs/development/metrics.md
  go.mod
  pkg/metrics/metrics.go
  pkg/metrics/metrics_suite_test.go
  pkg/metrics/metrics_test.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/l, merge/squash

#606 Documentation: added a scale-up doc.
  docs/concepts/images/scale-up-sequenceDiagram.png
  docs/concepts/scale-up-sequenceDiagram.txt
  docs/concepts/scale-up.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#627 Exclude outdated client-go in `go.mod`
  go.mod
  go.sum
  vendor/modules.txt
Labels: area/dev-productivity, kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s
