Repository gardener/etcd-druid, pull requests merged in 2024-08, with the labels that each got.

#847 Upgrade etcd-backup-restore-distroless image from `v0.28.2` to `v0.28.3`
  charts/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#823 Fix statefulset `PreSync` to work for certain cases of unhealthy etcd clusters upon druid upgrade
  api/v1alpha1/helper.go
  internal/component/statefulset/statefulset.go
Labels: area/quality, kind/bug, needs/ok-to-test, needs/review, reviewed/ok-to-test, size/s

#850 Compaction job shouldn't add cluster-autoscaler.kubernetes.io/safe-to-evict: "false" annotation to compaction pod.
  controllers/compaction/reconciler.go
Labels: area/cost, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#845 Compaction job shouldn't add `cluster-autoscaler.kubernetes.io/safe-to-evict: "false"` annotation to compaction pod.
  internal/controller/compaction/reconciler.go
  internal/controller/compaction/register_test.go
Labels: area/cost, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s, merge/squash, needs/cherry-pick

#851 Update README.md
  README.md
  docs/README.md
  docs/assets/etcd-druid-demo.tape
  docs/images/controller.png
  docs/images/defrag.png
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/rebase, needs/changes, needs/review, needs/second-opinion, reviewed/do-not-merge, size/l

#853 Set CPU & Memory requests for compaction job
  internal/controller/compaction/reconciler.go
Labels: area/backup, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#855 PDB component sets `unhealthyPodEvictionPolicy` based on annotation
  internal/component/poddistruptionbudget/poddisruptionbudget.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#833 Enhance `E2E` Test Suite to support Parallel Execution
  Makefile
  hack/e2e-test/run-e2e-test.sh
  test/e2e/etcd_backup_test.go
  test/e2e/etcd_compaction_test.go
  test/e2e/etcd_multi_node_test.go
  test/e2e/resources/tls/ca.srl
  test/e2e/resources/tls/server.crt
  test/e2e/resources/tls/server.csr
  test/e2e/resources/tls/server.csr.conf
  test/e2e/resources/tls/server.key
  test/e2e/suite_test.go
  test/e2e/utils.go
Labels: kind/enhancement, needs/ok-to-test, needs/changes, needs/review, needs/second-opinion, size/xl, area/testing

#862 Fixed broken links - 2024.08
  docs/proposals/01-multi-node-etcd-clusters.md
  docs/proposals/05-etcd-operator-tasks.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#861 Switch from deprecated pkg `k8s.io/utils/pointer` to recommended `k8s.io/utils/ptr` for pointer operations
  Makefile
  api/v1alpha1/helper.go
  api/v1alpha1/helper_test.go
  api/validation/etcd_test.go
  api/validation/etcdcopybackupstask_test.go
  docs/README.md
  hack/tools.mk
  internal/component/clientservice/clientservice.go
  internal/component/clientservice/clientservice_test.go
  internal/component/configmap/configmap_test.go
  internal/component/configmap/etcdconfig.go
  internal/component/peerservice/peerservice.go
  internal/component/peerservice/peerservice_test.go
  internal/component/poddistruptionbudget/poddisruptionbudget.go
  internal/component/serviceaccount/serviceaccount.go
  internal/component/statefulset/builder.go
  internal/component/statefulset/statefulset.go
  internal/component/statefulset/statefulset_test.go
  internal/component/statefulset/stsmatcher.go
  internal/controller/compaction/reconciler.go
  internal/controller/compaction/register_test.go
  internal/controller/etcd/reconcile_status.go
  internal/controller/etcd/register_test.go
  internal/controller/etcdcopybackupstask/reconciler.go
  internal/controller/etcdcopybackupstask/reconciler_test.go
  internal/errors/errors.go
  internal/health/condition/check_data_volumes_ready_test.go
  internal/health/etcdmember/builder_test.go
  internal/health/etcdmember/check_ready_test.go
  internal/health/status/check_test.go
  internal/store/store_test.go
  internal/utils/envvar.go
  internal/utils/image.go
  internal/utils/miscellaneous.go
  internal/webhook/util/decode.go
  test/e2e/etcd_multi_node_test.go
  test/e2e/utils.go
  test/integration/controllers/compaction/reconciler_test.go
  test/integration/controllers/etcdcopybackupstask/reconciler_test.go
  test/it/controller/etcd/assertions.go
  test/it/controller/etcd/helper.go
  test/it/controller/etcd/reconciler_test.go
  test/utils/etcd.go
  test/utils/etcdcopybackupstask.go
  test/utils/imagevector.go
  test/utils/lease.go
  test/utils/misc.go
  test/utils/statefulset.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, reviewed/do-not-merge, size/xl

#864 Fix `.ci/component_descriptor` script
  .ci/hack/component_descriptor
Labels: area/delivery, kind/bug, needs/ok-to-test, reviewed/lgtm, size/s
