Repository gardener/etcd-druid, pull requests merged in 2024-09, with the labels that each got.

#866 Upgrade etcd-backup-restore-distroless: `v0.28.3` -> `v0.28.4`
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#874 Fix peer TLS enablement during scale-up of etcd cluster
  internal/component/rolebinding/rolebinding.go
  internal/component/statefulset/statefulset.go
  internal/utils/lease.go
  internal/utils/lease_test.go
  test/it/controller/etcd/helper.go
  test/it/controller/etcd/reconciler_test.go
Labels: area/quality, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#856 Remove usage of *_STORAGE_API_ENDPOINT` environment variables for providers
  config/samples/etcd-secret-azurite.yaml
  hack/ci-e2e-kind-azure.sh
  internal/common/constants.go
  internal/store/store.go
  test/e2e/utils.go
  test/integration/controllers/compaction/reconciler_test.go
Labels: area/security, kind/task, needs/ok-to-test, needs/changes, needs/review, size/s

#876 Fix `make deploy-debug`
  Makefile
  skaffold.yaml
Labels: area/dev-productivity, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#873 Enhance the `docker-build` make target to build for multiple platforms.
  Makefile
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#878 [hotfix-v0.22] Set CPU & Memory requests for compaction job (#853)
  controllers/compaction/reconciler.go
Labels: kind/enhancement, needs/ok-to-test, needs/review, size/xs

#880 upgrade to greatest patch-version of etc-custom-image
  charts/images.yaml
Labels: area/delivery, kind/cleanup, needs/ok-to-test, needs/changes, needs/review, size/xs
