Repository gardener/etcd-druid, pull requests merged in 2024-07, with the labels that each got.

#824 Fix broken links - 2024.07
  docs/concepts/controllers.md
  docs/development/getting-started-locally-localstack.md
  docs/operations/recovery-from-permanent-quorum-loss-in-etcd-cluster.md
  docs/proposals/01-multi-node-etcd-clusters.md
  docs/proposals/05-etcd-operator-tasks.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/changes, needs/review, size/s

#826 Update golang version to 1.22 and adapt loop var improvements
  .ci/pipeline_definitions
  Dockerfile
  go.mod
  internal/component/memberlease/memberlease.go
  internal/component/snapshotlease/snapshotlease.go
  internal/controller/etcd/reconcile_delete.go
  internal/health/condition/builder.go
Labels: area/dev-productivity, area/quality, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#825 Upgrade etcd-backup-restore from v0.24.8-> v0.24.9 and etcd-backup-restore-distroless from v0.28.0 -> v0.29.0
  internal/images/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#822 Fix and include unit tests for health package
  Makefile
  internal/controller/etcd/register_test.go
  internal/health/condition/check_all_members.go
  internal/health/condition/check_data_volumes_ready.go
  internal/health/condition/check_data_volumes_ready_test.go
  internal/health/etcdmember/check_ready_test.go
  internal/health/status/check_test.go
  internal/utils/statefulset.go
  test/it/controller/etcd/helper.go
  test/it/controller/etcd/reconciler_test.go
  test/utils/client.go
  test/utils/configmap.go
  test/utils/iterator.go
  test/utils/misc.go
  test/utils/rbac.go
  test/utils/service.go
  test/utils/statefulset.go
Labels: kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xl, area/testing

#804 Add new labels to sts pods, for backward compatibility with v0.23.0, which includes #777
  api/v1alpha1/types_etcd.go
  controllers/etcd/reconciler.go
  pkg/component/etcd/statefulset/statefulset.go
  pkg/component/etcd/statefulset/statefulset_test.go
  pkg/component/etcd/statefulset/values.go
  pkg/component/etcd/statefulset/values_helper.go
  pkg/health/etcdmember/check_ready.go
  pkg/health/etcdmember/check_ready_test.go
  pkg/utils/labels.go
  pkg/utils/statefulset.go
  test/integration/controllers/etcd/reconciler_test.go
  test/utils/statefulset.go
Labels: area/quality, kind/task, needs/ok-to-test, needs/review, needs/second-opinion, size/l

#827 Upgrade etcd-backup-restore-distroless from v0.28.0 -> v0.28.1
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#828 Minimize probability of race condition between etcd and custodian controllers for etcd status updates
  controllers/etcd/reconciler.go
Labels: area/quality, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#829 Upgrade etcd-backup-restore-distroless image from v0.28.1 to v0.28.2
  charts/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#830 Upgrade `github.com/gardener/etcd-backup-restore` dependency from 0.26.0 to 0.29.0
  go.mod
  go.sum
Labels: area/open-source, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#753 Enable `etcd-druid` to make use of `Azurite` - the Azure Blob Storage Emulator
  Makefile
  config/samples/druid_v1alpha1_etcd_azurite.yaml
  config/samples/etcd-secret-azurite.yaml
  docs/development/getting-started-locally-azurite.md
  hack/addlicenseheaders.sh
  hack/ci-e2e-kind-azure.sh
  hack/deploy-azurite.sh
  hack/e2e-test/infrastructure/azurite/azurite.yaml
  hack/e2e-test/infrastructure/kind/cluster.yaml
  hack/e2e-test/infrastructure/overlays/azure/common/azure.env
  hack/e2e-test/infrastructure/overlays/azure/common/files/common.sh
  internal/common/constants.go
  internal/store/store.go
  internal/webhook/util/decode.go
  internal/webhook/util/miscellaneous.go
  test/e2e/utils.go
  test/integration/controllers/compaction/reconciler_test.go
  test/utils/manager.go
Labels: area/cost, area/dev-productivity, area/usability, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, reviewed/do-not-merge, size/l, platform/azure, area/testing

#832 Add the pkg.go.dev badge to `README.md`
  README.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/review, reviewed/lgtm, size/xs

#835 Fixes pre-deploy step having incorrect desired labels and adds a temp fix for race condition
  controllers/custodian/reconciler.go
  controllers/predicate/predicate.go
  controllers/utils/reconciler.go
  pkg/component/etcd/statefulset/statefulset.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#840 Fixed broken links - 2024.07
  docs/operations/restoring-single-member-in-multi-node-etcd-cluster.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#839 Fix integration tests by ensuring necessary pods are created
  test/integration/controllers/etcd/reconciler_test.go
  test/utils/misc.go
  test/utils/statefulset.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/s, area/testing

#841 Statefulset PreDeploy flow checks for pod readiness if labels were patched
  pkg/component/etcd/statefulset/statefulset.go
Labels: area/quality, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#834 removed g/g scripts dependency, updated gomod dependencies, adapted g…
  Makefile
  README.md
  api/v1alpha1/etcd_test.go
  api/v1alpha1/helper_test.go
  charts/druid/charts/crds/templates/crd-druid.gardener.cloud_etcdcopybackupstasks.yaml
  charts/druid/charts/crds/templates/crd-druid.gardener.cloud_etcds.yaml
  config/crd/bases/crd-druid.gardener.cloud_etcdcopybackupstasks.yaml
  config/crd/bases/crd-druid.gardener.cloud_etcds.yaml
  go.mod
  go.sum
  hack/check-generate.sh
  hack/check.sh
  hack/clean.sh
  hack/kind-up.sh
  hack/test-cover-clean.sh
  hack/test.sh
  hack/tools.go
  hack/tools.mk
  internal/component/clientservice/clientservice_test.go
  internal/component/configmap/configmap_test.go
  internal/component/memberlease/memberlease_test.go
  internal/component/peerservice/peerservice_test.go
  internal/component/poddistruptionbudget/poddisruptionbudget_test.go
  internal/component/role/role_test.go
  internal/component/rolebinding/rolebinding_test.go
  internal/component/serviceaccount/serviceaccount_test.go
  internal/component/snapshotlease/snapshotlease_test.go
  internal/component/statefulset/builder.go
  internal/component/statefulset/statefulset_test.go
  internal/controller/compaction/reconciler.go
  internal/controller/compaction/register.go
  internal/controller/compaction/register_test.go
  internal/controller/etcd/register.go
  internal/controller/etcd/register_test.go
  internal/controller/etcdcopybackupstask/reconciler.go
  internal/errors/errors_test.go
  internal/health/condition/check_backup_ready_test.go
  internal/health/condition/check_data_volumes_ready.go
  internal/health/etcdmember/check_ready.go
  internal/manager/manager.go
  internal/mock/controller-runtime/client/mocks.go
  internal/mock/controller-runtime/manager/mocks.go
  internal/store/store_test.go
  internal/utils/conditions_test.go
  internal/utils/labels_test.go
  internal/utils/lease_test.go
  internal/utils/statefulset_test.go
  internal/webhook/etcdcomponents/handler_test.go
  test/it/controller/etcd/helper.go
  test/utils/statefulset.go
Labels: area/open-source, area/quality, kind/technical-debt, kind/cleanup, needs/ok-to-test, needs/second-opinion, size/xl

#842 Fix build information in logs
  .ci/build
  Makefile
  skaffold.yaml
Labels: area/logging, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#844 Fix VPA dependency in go.mod
  go.mod
  go.sum
Labels: area/quality, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#846 Fix make docker-build.
  Makefile
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs
