Repository gardener/etcd-druid, pull requests merged in 2024-01, with the labels that each got.

#745 Fix artifact registry issue
  Makefile
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#744 Move feature:etcd-wrapper from alpha to beta feature.
  docs/deployment/feature-gates.md
  pkg/features/features.go
  skaffold.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#746 Updates the etcd-wrapper version from v0.1 -> v0.1.1
  charts/images.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#756 [hotfix-v0.21] Cherry-pick essential PRs and bug fixes
  .ci/pipeline_definitions
  Makefile
  README.md
  api/v1alpha1/types_etcd_test.go
  charts/druid/values.yaml
  charts/images.yaml
  config/default/manager_image_patch.yaml
  pkg/component/etcd/statefulset/statefulset_test.go
  skaffold.yaml
  test/integration/controllers/compaction/reconciler_test.go
  test/utils/etcd.go
  test/utils/etcdcopybackupstask.go
Labels: area/backup, kind/bug, needs/ok-to-test, needs/review, size/s

#755 Make `max-backups` configurable in LimitBased GC from etcd yaml with a new field `maxBackupsLimitBasedGC` in Etcd CR
  api/v1alpha1/types_etcd.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/druid/charts/crds/templates/10-crd-druid.gardener.cloud_etcds.yaml
  config/crd/bases/10-crd-druid.gardener.cloud_etcds.yaml
  pkg/component/etcd/statefulset/values.go
  pkg/component/etcd/statefulset/values_helper.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, needs/changes, needs/review, size/xs, merge/squash

#758 Add etcd team to component descriptor
  .ci/pipeline_definitions
Labels: area/delivery, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
