Repository gardener/etcd-druid, pull requests merged in 2024-06, with the labels that each got.

#806 Fix spacing on document `etcd-network-latency.md`
  docs/development/etcd-network-latency.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#805 Use localstack-s3 image instead of localstack
  hack/e2e-test/infrastructure/localstack/localstack.yaml
Labels: area/dev-productivity, area/storage, kind/test, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, reviewed/do-not-merge, size/xs

#786 Add the `vendor` directory to `.gitignore`
  .gitignore
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, reviewed/do-not-merge, size/xs

#817 Don't add `StorageClassName` in pvcClaim if StorageClass is empty string
  go.mod
  go.sum
  internal/component/statefulset/builder.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#816 Fixes reuse compliance
  .reuse/dep5
  LICENSES/BSD-2-Clause.txt
  LICENSES/BSD-3-Clause.txt
  LICENSES/ISC.txt
  LICENSES/MIT.txt
  LICENSES/MPL-2.0.txt
Labels: kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xl, area/compliance
