Repository gardener/etcd-druid, pull requests merged in 2025-08, with the labels that each got.

#1135 migrate CICD-Pipeline to GitHub-Actions
  .ci/build
  .ci/check
  .ci/common.sh
  .ci/component_descriptor
  .ci/hack/component_descriptor
  .ci/pipeline_definitions
  .ci/test
  .github/workflows/build.yaml
  .github/workflows/non-release.yaml
  .github/workflows/release.yaml
  .github/workflows/upgrade-dependencies.yaml
  .ocm/base-component.yaml
Labels: area/delivery, kind/technical-debt, kind/task, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/l

#1138 fix typo in code block
  docs/usage/recovering-etcd-clusters.md
Labels: area/usability, kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#1154 Convert `.reuse/dep5` to `REUSE.toml`
  .reuse/dep5
  REUSE.toml
Labels: area/open-source, kind/task, needs/changes, needs/review, reviewed/ok-to-test, size/s

#1157 Update the build badge from Concourse to GitHub Actions
  README.md
Labels: area/delivery, kind/cleanup, reviewed/ok-to-test, reviewed/lgtm, size/xs

#1156 Fix permissions for mkdocs GHA workflow
  .github/workflows/publish-docs.yml
Labels: area/documentation, area/open-source, kind/bug, needs/review, reviewed/ok-to-test, size/xs
