Repository gardener/etcd-druid, pull requests merged in 2025-09, with the labels that each got.

#1162 To include release notes from sub-component i.e etcdbr.
  .github/workflows/release.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xs

#1166 Reduce the default value of snapshot-count from 75k to 10k.
  api/core/v1alpha1/etcd_test.go
  examples/client/main.go
  internal/component/configmap/etcdconfig.go
  test/e2e/utils.go
  test/utils/etcd.go
Labels: area/high-availability, kind/enhancement, needs/review, reviewed/ok-to-test, size/xs, area/auto-scaling

#1174 Fix CI build status marker in website
  docs/index.md
Labels: area/open-source, area/usability, kind/bug, needs/review, reviewed/ok-to-test, size/xs
