Repository gardener/etcd-druid, pull requests merged in 2025-04, with the labels that each got.

#1053 CEL expression to invalidate setting/unsetting of immutable fields.
  api/core/v1alpha1/crds/druid.gardener.cloud_etcds.yaml
  api/core/v1alpha1/etcd.go
  test/it/crdvalidation/etcd/specupdate_test.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, reviewed/lgtm, size/s

#1058 Switch Slack references to Gardener workspace
  .github/ISSUE_TEMPLATE/support.md
Labels: area/open-source, kind/enhancement, needs/review, size/xs

#1038 Forbid container privilege escalations for ETCD Druid component containers
  charts/templates/deployment.yaml
  internal/component/statefulset/builder.go
  internal/controller/compaction/reconciler.go
  internal/controller/etcdcopybackupstask/reconciler.go
  internal/health/etcdmember/check_ready_test.go
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s, area/compliance

#1070 Re-introduce `/scale` subresource for Etcd CRD
  api/core/v1alpha1/crds/druid.gardener.cloud_etcds.yaml
  api/core/v1alpha1/crds/druid.gardener.cloud_etcds_without_cel.yaml
  api/core/v1alpha1/etcd.go
  docs/api-reference/etcd-druid-api.md
  docs/usage/managing-etcd-clusters.md
  internal/controller/etcd/reconcile_status.go
  test/it/controller/etcd/reconciler_test.go
Labels: kind/enhancement, needs/ok-to-test, needs/review, size/m, status/closed, area/auto-scaling, area/scalability

#1073 Upgrade `.ci/pipeline_definitions` and `Dockerfile` to Go 1.24.2.
  .ci/pipeline_definitions
  Dockerfile
Labels: area/quality, area/security, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#1074 Upgrade `.ci/pipeline_definitions` and `Dockerfile` to Go 1.24.2. (#1073)
  .ci/pipeline_definitions
  Dockerfile
Labels: area/quality, area/security, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#1076 Upgrade etcd-backup-restore from v0.35.1 to v0.35.2 (#1075)
  internal/images/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs
