Repository gardener/etcd-druid, pull requests merged in 2025-05, with the labels that each got.

#1088 Augment `Etcd` API with `runAsRoot`
  api/core/v1alpha1/crds/druid.gardener.cloud_etcds.yaml
  api/core/v1alpha1/crds/druid.gardener.cloud_etcds_without_cel.yaml
  api/core/v1alpha1/etcd.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  docs/api-reference/etcd-druid-api.md
  go.work.sum
  internal/component/statefulset/builder.go
  internal/component/statefulset/stsmatcher.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, needs/changes, needs/review, needs/second-opinion, size/l

#1091 Fix the etcd controller bug where the first reconciliation errors.
  api/core/v1alpha1/crds/druid.gardener.cloud_etcds.yaml
  api/core/v1alpha1/crds/druid.gardener.cloud_etcds_without_cel.yaml
  api/core/v1alpha1/etcd.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  go.work.sum
  internal/controller/etcd/reconcile_status.go
Labels: area/quality, kind/bug, needs/ok-to-test, needs/second-opinion, size/l

#1099 Revert Bump PRs k8s.io from 0.32.3 to 0.33.0
  api/core/v1alpha1/crds/druid.gardener.cloud_etcds.yaml
  api/core/v1alpha1/crds/druid.gardener.cloud_etcds_without_cel.yaml
  api/go.mod
  api/go.sum
  client/go.mod
  client/go.sum
  go.mod
  go.sum
  go.work.sum
Labels: needs/ok-to-test, needs/review, size/m

#1086 Configurable ports
  api/core/v1alpha1/crds/druid.gardener.cloud_etcds.yaml
  api/core/v1alpha1/crds/druid.gardener.cloud_etcds_without_cel.yaml
  api/core/v1alpha1/etcd.go
  api/core/v1alpha1/etcd_test.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  docs/api-reference/etcd-druid-api.md
  examples/client/main.go
  internal/component/clientservice/clientservice_test.go
  internal/component/statefulset/builder.go
  internal/component/statefulset/stsmatcher.go
  test/e2e/utils.go
  test/utils/etcd.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, needs/rebase, needs/review, needs/second-opinion, size/s

#1100 Use `/root` as home dir instead of `/home/nonroot` when running as `root`
  internal/component/statefulset/builder.go
  internal/component/statefulset/stsmatcher.go
  internal/controller/compaction/reconciler.go
  internal/utils/kubernetes/store.go
  internal/utils/kubernetes/store_test.go
  test/utils/etcd.go
Labels: area/usability, kind/bug, needs/ok-to-test, needs/review, size/m

#1103 Remove functionality that deletes old ConfigMaps
  api/core/v1alpha1/helper.go
  internal/component/configmap/configmap.go
  internal/controller/etcd/reconcile_spec.go
Labels: area/quality, kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s
