Repository gardener/etcd-druid, pull requests merged in 2025-03, with the labels that each got.

#1013 Housekeeping: fix links, remove deprecated labels in examples, use stdlib `maps.Copy`, etc
  docs/index.md
  docs/monitoring/metrics.md
  examples/objstore-emulator/etcd-secret-azurite.yaml
  examples/objstore-emulator/etcd-secret-localstack.yaml
  internal/metrics/metrics.go
  test/e2e/utils.go
Labels: area/dev-productivity, area/documentation, kind/cleanup, needs/ok-to-test, needs/review, size/s

#1014 Cleanup older configmaps with the naming format `etcd-bootstrap-UID[:6]`
  api/core/v1alpha1/helper.go
  internal/component/configmap/configmap.go
  internal/component/types.go
  internal/controller/etcd/reconcile_spec.go
Labels: area/quality, kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#995 CRD Validation for Etcd resource using CEL expressions
  Makefile
  api/core/crds/crd.go
  api/core/crds/crd_test.go
  api/core/crds/druid.gardener.cloud_etcds.yaml
  api/core/crds/druid.gardener.cloud_etcds_without_cel.yaml
  api/core/v1alpha1/etcd.go
  api/hack/generate.sh
  docs/api-reference/etcd-druid-api.md
  docs/concepts/etcd-cluster-components.md
  docs/usage/validating-etcd-clusters.md
  examples/etcd/druid_v1alpha1_etcd.yaml
  examples/etcd/druid_v1alpha1_etcd_azurite.yaml
  examples/etcd/druid_v1alpha1_etcd_fakegcs.yaml
  examples/etcd/druid_v1alpha1_etcd_localstack.yaml
  go.mod
  go.work.sum
  hack/prepare-chart-resources.sh
  hack/test-go.sh
  hack/tools.mk
  test/e2e/suite_test.go
  test/e2e/utils.go
  test/it/assets/assets.go
  test/it/controller/assets/assets.go
  test/it/controller/etcd/helper.go
  test/it/controller/etcd/reconciler_test.go
  test/it/crdvalidation/etcd/helper.go
  test/it/crdvalidation/etcd/specbackup_test.go
  test/it/crdvalidation/etcd/specetcd_test.go
  test/it/crdvalidation/etcd/specsharedconfig_test.go
  test/it/crdvalidation/etcd/specupdate_test.go
  test/it/crdvalidation/etcd/validation_test.go
  test/utils/etcd.go
  test/utils/namespace.go
Labels: area/control-plane, area/open-source, area/quality, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xl

#1024 Change GetAll CRD API to return a Map with keys as CRD name
  api/core/crds/crd.go
  api/core/crds/crd_test.go
  test/it/assets/assets.go
  test/it/crdvalidation/etcd/helper.go
  test/it/crdvalidation/etcd/specetcd_test.go
  test/it/crdvalidation/etcd/specsharedconfig_test.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#1026 Move CRDs and respective API to be under v1alpha1
  README.md
  api/core/v1alpha1/crds/crd.go
  api/core/v1alpha1/crds/crd_test.go
  api/core/v1alpha1/crds/druid.gardener.cloud_etcdcopybackupstasks.yaml
  api/core/v1alpha1/crds/druid.gardener.cloud_etcds.yaml
  api/core/v1alpha1/crds/druid.gardener.cloud_etcds_without_cel.yaml
  api/hack/generate.sh
  docs/deployment/getting-started-locally/getting-started-locally.md
  docs/deployment/prepare-helm-charts.md
  docs/index.md
  hack/prepare-chart-resources.sh
  test/integration/controllers/assets/assets.go
  test/it/assets/assets.go
  test/it/controller/etcd/reconciler_test.go
  test/it/crdvalidation/etcd/validation_test.go
Labels: area/control-plane, kind/api-change, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#1027 Remove the direct depedency on `gopkg.in/yaml.v2`.
  go.mod
  go.sum
  internal/component/configmap/configmap.go
  internal/component/configmap/etcdconfig.go
Labels: area/dev-productivity, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/s, dependencies

#1032 Temporarily remove CEL validations for StorageCapacity
  api/core/v1alpha1/crds/druid.gardener.cloud_etcds.yaml
  api/core/v1alpha1/etcd.go
  test/it/crdvalidation/etcd/helper.go
  test/it/crdvalidation/etcd/specbackup_test.go
  test/it/crdvalidation/etcd/specetcd_test.go
  test/it/crdvalidation/etcd/specsharedconfig_test.go
  test/it/crdvalidation/etcd/specupdate_test.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#1030 Fixed broken links - 2025.03
  docs/deployment/getting-started-locally/getting-started-locally.md
  docs/development/add-new-etcd-cluster-component.md
  docs/proposals/05-etcd-operator-tasks.md
  docs/proposals/06-immutable-etcd-backups.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/changes, needs/review, size/xs

#1034 Reverted one change which was introduced to reduce flakiness in e2e tests.
  test/e2e/utils.go
Labels: kind/test, needs/ok-to-test, needs/review, size/xs, area/testing

#1036 Removed bump_tag and its invocation from CI pipeline_definition
  .ci/bump_tag
  .ci/pipeline_definitions
Labels: area/delivery, kind/bug, needs/ok-to-test, needs/review, size/xs

#1042 Bump versions of tools used for tests and checks. (`gosec` bump fixes the CI)
  hack/tools.mk
Labels: area/dev-productivity, kind/task, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/testing

#1043 Add nodeSelector, tolerations, affinity & topologySpreadConstraints to charts
  charts/templates/deployment.yaml
  charts/values.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, needs/review, size/xs, needs-ok-to-test

#1044 Fix charts by placing `volumeMounts` in the `containers` section of the pod spec.
  charts/templates/deployment.yaml
Labels: area/delivery, kind/regression, needs/ok-to-test, needs/review, size/xs

#1039 Enhance compaction metrics by segregating them into various categories
  internal/controller/compaction/metrics.go
  internal/controller/compaction/reconciler.go
  internal/controller/compaction/reconciler_test.go
  internal/controller/compaction/register_test.go
  internal/metrics/metrics.go
  test/integration/controllers/compaction/reconciler_test.go
Labels: area/monitoring, kind/enhancement, needs/ok-to-test, needs/changes, needs/review, needs/second-opinion, size/xl

#1046 Do not specify a value for `nodeSelector` in `charts/values.yaml`.
  charts/values.yaml
Labels: area/delivery, area/open-source, kind/cleanup, needs/ok-to-test, needs/review, size/xs
