Repository gardener/etcd-druid, pull requests merged in 2025-01, with the labels that each got.

#741 Enable Druid to use GCS Emulator for local setup & run e2e tests
  Makefile
  config/samples/druid_v1alpha1_etcd_fakegcs.yaml
  config/samples/etcd-secret-fakegcs.yaml
  docs/deployment/getting-started-locally/getting-started-locally.md
  docs/deployment/getting-started-locally/manage-azurite-emulator.md
  docs/deployment/getting-started-locally/manage-gcs-emulator.md
  docs/deployment/getting-started-locally/manage-s3-emulator.md
  docs/development/running-e2e-tests.md
  hack/ci-e2e-kind-gcs.sh
  hack/deploy-fakegcs.sh
  hack/e2e-test/infrastructure/fake-gcs-server/fake-gcs-server.yaml
  hack/e2e-test/infrastructure/overlays/gcp/common/files/common.sh
  hack/e2e-test/infrastructure/overlays/gcp/common/gcp.env
  hack/kind-up.sh
  hack/kind/cluster.yaml
  test/e2e/utils.go
Labels: area/dev-productivity, kind/enhancement, kind/test, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/l, area/testing

#962 Update github PR template
  .github/pull_request_template.md
  api/v1alpha1/zz_generated.deepcopy.go
Labels: area/open-source, kind/task, needs/ok-to-test, needs/review, size/xs

#980 Dowgrade k8s.io packages to v0.31.5
  go.mod
  go.sum
Labels: needs/ok-to-test

#982 Dowgrade k8s.io packages to v0.31.5 (#980)
  go.mod
  go.sum
Labels: needs/ok-to-test

#983 Fix broken links - 2025.01
  docs/development/running-e2e-tests.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#986 Update golang version to 1.23.5
  .ci/pipeline_definitions
  Dockerfile
Labels: area/quality, area/security, kind/task, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/compliance

#973 Allow specifying traffic distribution preference for the etcd client Service
  api/v1alpha1/etcd.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/druid/charts/crds/templates/crd-druid.gardener.cloud_etcds.yaml
  config/crd/bases/crd-druid.gardener.cloud_etcds.yaml
  config/samples/druid_v1alpha1_etcd.yaml
  config/samples/druid_v1alpha1_etcd_azurite.yaml
  config/samples/druid_v1alpha1_etcd_fakegcs.yaml
  config/samples/druid_v1alpha1_etcd_localstack.yaml
  docs/api-reference/etcd-druid-api.md
  internal/component/clientservice/clientservice.go
  internal/component/clientservice/clientservice_test.go
  test/utils/etcd.go
Labels: area/high-availability, area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m
