Repository gardener/etcd-druid, pull requests merged in 2025-07, with the labels that each got.

#1132 Fixes helm chart service template to correctly use .Values.enabledOperatorConfig
  charts/templates/_helpers.tpl
  charts/templates/deployment.yaml
  charts/templates/operatorconfigmap.yaml
  charts/templates/service.yaml
  charts/values.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, needs/review, size/m

#1134 Fix compaction e2e test setup in skaffold profile
  skaffold.yaml
Labels: kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/testing

#1133 Fix etcd-wrapper related tls config flags
  internal/component/statefulset/builder.go
  internal/component/statefulset/stsmatcher.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/s, area/user-management
